### ISSUE TITLE
Handle Japanese title queries

### ISSUE THREAD

**Issue by f4ngy** [mczub/because-moe#2]
I think there's a good chance that people who are looking for a legal way to watch a show will not yet know the localized title and will instead try searching for the Japanese title (i.e. "Ore Monogatari" instead of looking for "My Love Story"). Adding the ability to search based on Japanese tile (if possible) will make this tool even more useful.

I'm not sure if this could be used http://myanimelist.net/modules.php?go=api#animemangasearch but it looks like the title field on MAL is usually the Japanese title, so perhaps you could search for the English title and then grab the Japanese title from the response?

**Comment by mczub** [comment]
This is now implemented in https://github.com/mczub/because-moe/pull/10
